#!/usr/bin/env python3
import csv
import urllib.request
import sys
import re
from collections import Counter

URL_OGN = "https://ddb.glidernet.org/download/"
URL_FLARM = "https://www.flarmnet.org/files/ddb.csv"
DATA_FLARM = "ddb.csv"
DATA_OGN = 'index.html'

def download_csv(url):
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8", errors="replace")

def open_csv(url):
    with open(url, 'r') as f:
        data = f.read()
    return data

def parse_csv(text):
    rows = []
    r = csv.reader(text.splitlines())
    header = next(r)   # skip header

    for row in r:
        dev_type = row[0].strip().strip("'")
        hexcode  = row[1].strip().strip("'")
        reg      = row[3].strip().strip("'")   # callsign/registration

        reg = re.sub(r'\s+', '', reg).upper()

        if not hexcode:
            continue

        # Skip empty callsigns smaller than 5 unless it starts with N
        # Skip callsigns starting with a number
        # Skip callsigns using 'TEST'
        if (len(reg) < 5 and (not reg.startswith('N'))) or re.match(r'^\d', reg) or re.search('TEST', reg) or re.search('GLIDER', reg) or re.search('TST', reg) or re.search('SOFTRF', reg):
            continue 

        # Skip ICAO
        if dev_type == 'I':
            continue

        rows.append((hexcode, dev_type, reg))
    return rows


def gen_cpp(rows):
    out = []
    out.append("#pragma once\n")
    out.append("// Auto-generated by ddb.py — DO NOT EDIT\n")
    out.append("#include <stdint.h>\n\n")

    # ----------------------------------------------------------------------
    # Build big string blob
    # ----------------------------------------------------------------------
    string_blob = []
    string_offsets = {}
    offsets = []
    offset = 0

    for hexcode, dev_type, reg in rows:
        if reg not in string_offsets:
            string_offsets[reg] = offset
            string_blob.append(reg + "\\0")
            offset += len(reg) + 1
        offsets.append(string_offsets[reg])

    if offset >= (1 << 24):
        raise ValueError(f"String blob too large for 24-bit offsets: {offset} bytes")

    # Emit string blob
    out.append("static constexpr char DDB_STRINGS[] __in_flash() =\n")
    for s in string_blob:
        escaped = s.replace("\\", "\\").replace('"', '\\"')
        out.append(f'    "{escaped}"\n')
    out.append(";\n\n")

    # ----------------------------------------------------------------------
    # Struct
    # ----------------------------------------------------------------------
    out.append(
        "struct DDBEntry {\n"
        "    uint8_t _offset[3];   // 24-bit offset into DDB_STRINGS\n"
        "    uint32_t offset() const {\n"
        "        return (uint32_t(_offset[0]) << 16) |\n"
        "               (uint32_t(_offset[1]) << 8)  |\n"
        "               (uint32_t(_offset[2]));\n"
        "    }\n"
        "    const char *reg() const { return &DDB_STRINGS[offset()]; }\n"
        "};\n\n"
        "static_assert(sizeof(DDBEntry) == 3, \"DDBEntry must remain packed\");\n\n"
    )

    # ----------------------------------------------------------------------
    # Search keys and DB entries
    # ----------------------------------------------------------------------
    out.append(f"static constexpr size_t DDB_COUNT = {len(rows)};\n\n")

    out.append("static constexpr uint16_t __in_flash() DDB_KEYS[DDB_COUNT] = {\n")
    for hexcode, dev_type, reg in rows:
        h = int(hexcode, 16)
        out.append(f"    0x{h & 0xFFFF:04X},\n")
    out.append("};\n\n")

    out.append("static constexpr DDBEntry __in_flash() DDB_DB[DDB_COUNT] = {\n")
    for i, (hexcode, dev_type, reg) in enumerate(rows):
        string_offset = offsets[i]
        b0 = (string_offset >> 16) & 0xFF
        b1 = (string_offset >> 8) & 0xFF
        b2 = string_offset & 0xFF
        out.append(f"    {{ {{ 0x{b0:02X}, 0x{b1:02X}, 0x{b2:02X} }} }},\n")
    out.append("};\n\n")

    # ----------------------------------------------------------------------
    # Build 256-bucket start index
    # ----------------------------------------------------------------------
    bucket_start = [0] * 257

    row_index = 0
    for bucket in range(256):
        bucket_start[bucket] = row_index
        while row_index < len(rows):
            h = int(rows[row_index][0], 16)
            if ((h >> 16) & 0xFF) != bucket:
                break
            row_index += 1
    bucket_start[256] = row_index

    out.append("static constexpr uint16_t __in_flash() DDB_BUCKET_START[257] = {\n")

    for value in bucket_start:
        out.append(f"    {value},\n")

    out.append("};\n")

    return "".join(out)

def show_duplicates(rows):
    col1_values = [row[0] for row in rows]
    counts = Counter(col1_values)
    duplicates = {value: count for value, count in counts.items() if count > 1}

    for value, count in duplicates.items():
        print(value, count)

def merge_flarm_ogn(flarm_data, ogn_data):
    # First, sort FLARM data to prioritize 'F' type over 'O' type
    flarm_sorted = sorted(flarm_data, key=lambda x: (0 if len(x) > 1 and x[1] == 'F' else 1))
    
    # Convert sorted flarm_data to a dictionary for quick lookup
    flarm_dict = {}
    for row in flarm_sorted:
        if len(row) >= 2:  # Ensure row has at least hex and type
            hex_code = row[0]
            # Only add if we haven't seen this hex code yet
            # This ensures 'F' types overwrite 'O' types for the same hex
            if hex_code not in flarm_dict:
                flarm_dict[hex_code] = row
    
    # Step 1: Add OGN data only if hex code doesn't exist in flarm_data
    for row in ogn_data:
        if len(row) >= 2:
            hex_code = row[0]
            if hex_code not in flarm_dict:
                flarm_dict[hex_code] = row
    
    # Convert back to list
    merged_data = list(flarm_dict.values())
        
    return merged_data

def validate_unique_hex(rows):
    counts = Counter(hexcode for hexcode, _, _ in rows)
    duplicates = {hexcode: count for hexcode, count in counts.items() if count > 1}
    if duplicates:
        raise ValueError(f"Duplicate hex codes found after merge: {duplicates}")

def drop_ogn_source_device_type_o(rows):
    return [row for row in rows if row[1] != 'O']

def swap_hex(rows):
    swapped_rows = []
    for hexcode, dev_type, reg in rows:
        h = int(hexcode, 16)
        b0 = (h >> 16) & 0xFF   # A
        b1 = (h >> 8)  & 0xFF   # B
        b2 = (h >> 0)  & 0xFF   # C

        swapped = (b2 << 16) | (b1 << 8) | b0  # CC BB AA
        swapped_hex = f"{swapped:06X}"

        swapped_rows.append((swapped_hex, dev_type, reg))
    return swapped_rows

# Main -------------------------------------------------------------------------
if __name__ == "__main__":
    ogn_data = parse_csv(download_csv(URL_OGN) )
    flarm_data = parse_csv(download_csv(URL_FLARM))

    # I use this somethimes to test the script to prevent to many requests from the webservice
    #ogn_data = parse_csv(open_csv(DATA_OGN))
    #flarm_data = parse_csv(open_csv(DATA_FLARM))

    # OGN source rows with device type 'O' are mostly gliders, paragliders, drones and
    # similar devices that are not useful for the FLARM-centric lookup DB.
    ogn_data = drop_ogn_source_device_type_o(ogn_data)

    merged_data = merge_flarm_ogn(flarm_data, ogn_data)
    validate_unique_hex(merged_data)
    merged_data = swap_hex(merged_data)

    # Sort by HEX for fast binary search
    merged_data.sort(key=lambda x: int(x[0], 16))

    cpp = gen_cpp(merged_data)
    sys.stdout.write(cpp)

    buckets = Counter((int(hexcode,16) >> 16) & 0xFF for hexcode,_,_ in merged_data)
    print("// ", max(buckets.values()), sum(buckets.values()) / 256)
