name: Build Project

inputs:
  test:
    description: 'Run tests'
    required: false
    default: 'false'
  build:
    description: 'Build the project'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Tests
      if: ${{ inputs.test == 'true' }}
      shell: bash
      run: |
        cd src
        cmake -B build_test -G Ninja && ninja -C build_test

    - name: Build Project
      if: ${{ inputs.build == 'true' }}
      shell: bash
      run: |
        export PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk/
        export FREERTOS_KERNEL_PATH=$GITHUB_WORKSPACE/FreeRTOS-Kernel
        cd src/pico
        cmake -B build -G Ninja && ninja -C build $1
        for file in build/*.uf2; do mv "$file" "build/develop_$(basename "$file")"; done
        ls -lrt build/*.uf2
