name: Build GaTas

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/gatas-build:latest
  TEST_TAG: ghcr.io/${{ github.repository }}/gatas-build:latest

jobs:
  Test:
    name: Run the unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GATAS
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get remove --purge gcc-11
          sudo apt-get install tree git ninja-build cmake gcc-12 

      - name: Build and Test
        uses: ./.github/actions/build_project
        with:
          test: 'true'

  Firmware:
    name: Firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { board: "pico_w", platform: "rp2040" }
          - { board: "pico2_w", platform: "rp2350" }

    steps:
      - name: Checkout GATAS
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment
        uses: ./.github/actions/setup_env

      - name: Build Firmware ${{ matrix.config.board }}
        uses: ./.github/actions/build_project
        with:
          build: 'true'
          board: ${{ matrix.config.board }}
          platform: ${{ matrix.config.platform }}

  Docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout GATAS
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: sudo apt-get install tree

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:src"
          push: true
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest

  Docker-Matrix:
    name: Firmware
    needs: Docker
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { board: "pico_w", platform: "rp2040" }
          - { board: "pico2_w", platform: "rp2350" }

    steps:
      - name: Checkout GATAS
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Pull and Run Container
        run: |
          docker pull ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
          cd src
          docker run --rm \
            -e PICO_PLATFORM=${{ matrix.config.platform }} \
            -e PICO_BOARD=${{ matrix.config.board }} \
            -v $(pwd):/opt/src \
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
