name: Build OpenAce

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenAce
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get remove --purge gcc-11
          sudo apt-get install tree git ninja-build cmake gcc-12 

      - name: Build and Test
        uses: ./.github/actions/build_project
        with:
          test: 'true'

    # action.yml
  Docker:
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/openace-build:latest

    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get install tree 

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:src"
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        run: |
          tree -d -L 3
          cd src
          docker run --rm -v $(pwd):/opt/src openace-build-image

  Firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenAce
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment
        uses: ./.github/actions/setup_env

      - name: Build and Test
        uses: ./.github/actions/build_project
        with:
          build: 'true'
