name: Build OpenAce

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - 'prerelease'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenAce
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get remove --purge gcc-11
          sudo apt-get install tree git ninja-build cmake gcc-12

      - name: Build and Test
        uses: ./.github/actions/build_project
        with:
          test: 'true'

  Firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenAce
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment
        uses: ./.github/actions/setup_env

      - name: Build and Test
        uses: ./.github/actions/build_project
        with:
          build: 'true'

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            src/pico/build/*.uf2
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            ./.github/develop.md
            ./.github/release.md
            LICENSE
          if-no-files-found: error

  PreRelease:
    needs: ["Test", "Firmware"]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/download-artifact@v4

      - name: Show artifacts
        shell: bash
        run: |
          find .

      - name: Push to Pre-Release
        if: startsWith(github.ref, 'refs/tags/prerelease')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: false
          name: Pre-Release
          body_path: documentation/.github/develop.md
          files: |
            ./documentation/.github/develop.md
            ./documentation/LICENSE
            ./firmware/OpenAce.uf2

      - name: Push to Release
        if: startsWith(github.ref, 'refs/tags/v*')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          name: Release
          body_path: documentation/.github/release.md
          files: |
            ./documentation/.github/release.md
            ./documentation/LICENSE
            ./firmware/OpenAce.uf2
