name: Release OpenAce

on:
 workflow_dispatch:
 push:
   tags:
     - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenAce
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment
        uses: ./.github/actions/setup_env

      - name: Build and Test
        uses: ./.github/actions/build_project

      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          name: Release
          body_path: .github/release.md
          files: |
            LICENSE
            src/pico/build/*.uf2
            .github/release.md
