name: Build GaTas

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - 'prerelease'

jobs:

  Test:
    name: Run the unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GA/TAS
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get remove --purge gcc-11 gcc-12 gcc-13
          sudo apt-get install -y tree git ninja-build cmake gcc-14

      - name: Build and Test
        uses: ./.github/actions/build_project
        with:
          test: 'true'


  Firmware:
    name: Build Firmware (RP2040 + RP2350)
    runs-on: ubuntu-latest
    needs: Test
    strategy:
      fail-fast: true
      matrix:
        platform:
          - { name: "rp2040", cmake_platform: "rp2040", board: "pico_w", outfile: "GATAS_rp2040.uf2" }
          - { name: "rp2350", cmake_platform: "rp2350", board: "pico2_w", outfile: "GATAS_rp2350-arm-s.uf2" }

    steps:
      - name: Checkout GA/TAS
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment
        uses: ./.github/actions/setup_env

      - name: Configure CMake
        shell: bash
        run: |
              export PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk/
              export FREERTOS_KERNEL_PATH=$GITHUB_WORKSPACE/FreeRTOS-Kernel
              cd src/pico
              cmake -B build_${{ matrix.platform.name }} \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DPICO_PLATFORM=${{ matrix.platform.cmake_platform }} \
                -DPICO_BOARD=${{ matrix.platform.board }} \
                -DGATAS_UART_OVER_USB=1

      - name: Build Firmware
        shell: bash
        run: |
              export PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk/
              export FREERTOS_KERNEL_PATH=$GITHUB_WORKSPACE/FreeRTOS-Kernel
              cd src/pico
              ninja -C build_${{ matrix.platform.name }}

      - name: Rename UF2
        shell: bash
        run: |
          # find the uf2 file
          cd src/pico
          UF2=$(find build_${{ matrix.platform.name }} -name "*.uf2" | head -n 1)
          cp "$UF2" "${{ matrix.platform.outfile }}"

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: src/pico/${{ matrix.platform.outfile }}
          if-no-files-found: error

  PreRelease:
    needs: ["Firmware"]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/download-artifact@v4

      - name: Show artifacts
        run: find .

      - name: Push to Pre-Release
        if: startsWith(github.ref, 'refs/tags/prerelease')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: false
          name: Pre-Release
          body_path: documentation/.github/develop.md
          files: |
            ./documentation/.github/develop.md
            ./documentation/LICENSE
            ./firmware/GATAS_rp2040.uf2
            ./firmware/GATAS_rp2350-arm-s.uf2

      - name: Push to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          name: Release
          body_path: documentation/.github/release.md
          files: |
            ./documentation/.github/release.md
            ./documentation/LICENSE
            ./firmware/GATAS_rp2040.uf2
            ./firmware/GATAS_rp2350-arm-s.uf2
